name             'kubernetes_helper'
maintainer       'Adam Edwards'
maintainer_email 'adamedx'
license          'Apache 2.0'
description      'Installs/Configures kubernetes_helper'
long_description 'Installs/Configures kubernetes_helper'
version          '0.1.33'

supports         'ubuntu'

depends          'resource'
depends          'git'
depends          'docker'
depends          'etcd'
depends          'curl'
depends          'runit'
depends          'golang'
depends          'build-essential'
